### ISSUE TITLE
example backend structure?

### ISSUE THREAD

**Issue by Analect** [datascienceinc/RestfulContentManager#1]
@AlecAivazis 
I had been searching for an alternative ContentManager other than the default file-system for Jupyter. I had previously looked at [PGContents](https://github.com/quantopian/pgcontents), but ideally wanted to find something that offered the possibility of version control. I happened upon your (this) implementation and wondered what sits on the back-end running the API server to which this RestfulContentManager interfaces. Could it feasibly integrate with something like a GitLab (or even Github) API?

Does the contents of this repo need to sit within a Jupyter notebook server and have some long-running  process running?  Or is it enough just to copy the code there?  Is there any public repo elsewhere you can point to that may have a sample running version of this, consuming an API, even a mocked-up one?

Thanks for any input on this.
Colum

**Comment by AlecAivazis** [comment]
Hey @Analect,

Sorry it took me so long to reply. Unfortunately, there isn't a public repo of the api server yet. Maybe when i get some time, I can throw one together for you. Or if you wanted to make one, I would be happy to add a link to the readme.

Until I make some actual documentation, the source code should have enough comments to give you a good sense of what's going on. The api runs as a separate service that manages an underlying storage method (mongodb, mysql, elastic search, etc.) This ContentManager is then configured to point to the API which it uses to query for notebooks, directories, files, and checkpoints following the description [here](http://jupyter-notebook.readthedocs.io/en/latest/extending/contents.html). 

I'm not sure if GitLab can be configured to provide an API that matches this but I'm fairly certain it wouldn't be possible with GitHub. The FIleContentManager assumes an immutable model for the checkpoints (they cannot be overwritten or deleted, only applied).

**Comment by Analect** [comment]
Thanks @AlecAivazis 
An example, as and when you get time would be much appreciated.
